# Generated by Django 4.2.2 on 2023-08-08 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="groups",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="groups",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.roles",
                verbose_name="Группа пользователей",
            ),
        ),
    ]
