# Generated by Django 4.2.2 on 2023-08-08 14:21

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_useraccount_roles_remove_useraccount_groups_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="roles",
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="groups",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="groups",
            field=models.ForeignKey(
                default=account.models.Roles.get_default_pk,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.roles",
                verbose_name="Группа пользователей",
            ),
        ),
    ]
