# Generated by Django 4.2.2 on 2023-08-08 14:29

import account.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("account", "0004_remove_useraccount_roles_remove_useraccount_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="roles",
            field=models.ForeignKey(
                default=account.models.Roles.get_default_pk,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.roles",
                verbose_name="Группа пользователей",
            ),
        ),
        migrations.RemoveField(
            model_name="useraccount",
            name="groups",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
    ]
