# Generated by Django 4.2.2 on 2023-09-11 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_useraccount_roles_remove_useraccount_groups_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="roles",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.roles",
                verbose_name="Группа пользователей",
            ),
        ),
    ]
