# Generated by Django 4.2.2 on 2023-07-27 13:49

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_news",
                    models.CharField(max_length=255, verbose_name="Название новости"),
                ),
                ("slug", models.SlugField(unique=True)),
                (
                    "picture_of_news",
                    models.FileField(upload_to=news.models.news_picture_upload_to),
                ),
                ("description", models.TextField(verbose_name="Описание новости")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "available_news",
                    models.BooleanField(default=False, verbose_name="Доступна"),
                ),
            ],
        ),
    ]
