# Generated by Django 4.2.2 on 2023-08-09 09:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options_alter_news_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                verbose_name="Описание новости"
            ),
        ),
    ]
