# Generated by Django 4.2.2 on 2023-08-09 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0003_alter_news_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="priority",
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
