# Generated by Django 4.2.2 on 2023-08-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_news_priority"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="short_description",
            field=models.CharField(
                default="Краткое описание",
                max_length=255,
                verbose_name="Краткое описание",
            ),
        ),
    ]
