# Generated by Django 4.2.2 on 2023-08-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_news_short_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="short_description",
            field=models.CharField(max_length=150, verbose_name="Краткое описание"),
        ),
    ]
