# Generated by Django 4.2.2 on 2023-08-16 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("instructions", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="instructions",
            options={"verbose_name": "Инструкция", "verbose_name_plural": "Инструкции"},
        ),
    ]
