# Generated by Django 4.2.2 on 2023-07-26 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("test_video", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypeMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_of_type", models.CharField(max_length=100, verbose_name="Тип")),
            ],
        ),
        migrations.AlterField(
            model_name="video",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name="video",
            name="type_media",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="test_video.typemedia",
            ),
            preserve_default=False,
        ),
    ]
