# Generated by Django 4.2.2 on 2023-08-09 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("test_video", "0003_video_content_for_roles"),
    ]

    operations = [
        migrations.RenameField(
            model_name="video",
            old_name="content_for_roles",
            new_name="roles",
        ),
    ]
