# Generated by Django 4.2.2 on 2023-08-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("material_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SectionMaterial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_of_section",
                    models.CharField(max_length=255, verbose_name="Название"),
                ),
                ("slug", models.SlugField(unique=True, verbose_name="ЧПУ")),
            ],
            options={
                "verbose_name": "Раздел",
                "verbose_name_plural": "Разделы",
                "db_table": "section_material",
            },
        ),
        migrations.AddField(
            model_name="material",
            name="selection",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="material_app.sectionmaterial",
                verbose_name="Раздел",
            ),
        ),
    ]
