# Generated by Django 4.2.2 on 2023-08-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("material_app", "0002_sectionmaterial_material_selection"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="SectionMaterial",
            new_name="SelectionMaterial",
        ),
        migrations.RenameField(
            model_name="selectionmaterial",
            old_name="name_of_section",
            new_name="name_of_selection",
        ),
        migrations.AlterModelTable(
            name="selectionmaterial",
            table="selection_material",
        ),
    ]
